services:
  dst-master:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_MASTER}
    restart: unless-stopped
    network_mode: host

    env_file:
      - ../.env

    volumes:
      - ../data:/data
      - ../config:/config
      - ../secrets:/secrets
      - ../mods:/mods

    command: /docker/start-master.sh

  dst-caves:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_CAVES}
    restart: unless-stopped
    network_mode: host

    env_file:
      - ../.env

    volumes:
      - ../data:/data
      - ../config:/config
      - ../secrets:/secrets
      - ../mods:/mods

    command: /docker/start-caves.sh