###############################################################################
# GAMECONCAK
# Don't Starve Together Cluster Configuration
###############################################################################

[GAMEPLAY]
game_mode = survival
max_players = 8
pause_when_empty = true
pvp = false

[NETWORK]
cluster_name = GAMECONCAK
cluster_description = chill server

cluster_password = alo113

cluster_intention = cooperative

offline_cluster = false
lan_only_cluster = false

[MISC]
console_enabled = true
max_snapshots = 10

[SHARD]
shard_enabled = true

bind_ip = 127.0.0.1

master_ip = 127.0.0.1
master_port = 10888

cluster_key = gameconcak_cluster