#!/bin/bash
set -e

############################################
# GAMECONCAK Local Mod Installer
############################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$PROJECT_DIR/.env"

SERVER_DIR="$PROJECT_DIR/data/server"
MODS_FILE="$PROJECT_DIR/mods/mods.txt"
SERVER_MODS_DIR="$SERVER_DIR/mods"

MASTER_MODOVERRIDES="$PROJECT_DIR/config/cluster/Master/modoverrides.lua"
CAVES_MODOVERRIDES="$PROJECT_DIR/config/cluster/Caves/modoverrides.lua"

STEAM_ROOT="$PROJECT_DIR/data/steam-workshop"
WORKSHOP_CONTENT_DIR="$STEAM_ROOT/steamapps/workshop/content/$WORKSHOP_APP_ID"

echo "===================================="
echo " GAMECONCAK Local Mod Installer"
echo "===================================="

if [ ! -f "$SERVER_DIR/bin64/dontstarve_dedicated_server_nullrenderer_x64" ]; then
    echo "ERROR: DST Dedicated Server not found."
    echo
    echo "Run:"
    echo "./scripts/update.sh"
    exit 1
fi

if [ ! -f "$MODS_FILE" ]; then
    echo "ERROR: $MODS_FILE not found."
    exit 1
fi

if ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
    echo "ERROR: Docker image not found."
    echo
    echo "Run:"
    echo "./scripts/build.sh"
    exit 1
fi

mkdir -p "$SERVER_MODS_DIR"
mkdir -p "$STEAM_ROOT"

MOD_IDS=()

while IFS= read -r LINE
do
    MOD_ID="$(echo "$LINE" | tr -d '[:space:]')"

    [[ -z "$MOD_ID" ]] && continue
    [[ "$MOD_ID" =~ ^# ]] && continue

    MOD_IDS+=("$MOD_ID")
done < "$MODS_FILE"

echo
echo "Syncing local mods with mods.txt..."

for MOD_DIR in "$SERVER_MODS_DIR"/workshop-*
do
    [ -d "$MOD_DIR" ] || continue

    MOD_NAME="$(basename "$MOD_DIR")"
    MOD_ID="${MOD_NAME#workshop-}"

    KEEP=false

    for ID in "${MOD_IDS[@]}"
    do
        if [ "$ID" = "$MOD_ID" ]; then
            KEEP=true
            break
        fi
    done

    if [ "$KEEP" = false ]; then
        echo "Removing unused $MOD_NAME..."
        rm -rf "$MOD_DIR"
    fi
done

for MOD_ID in "${MOD_IDS[@]}"
do
    DEST="$SERVER_MODS_DIR/workshop-$MOD_ID"

    if [ -f "$DEST/modinfo.lua" ]; then
        echo "Skip workshop-$MOD_ID: already installed."
        continue
    fi

    echo "Downloading workshop-$MOD_ID..."

    docker run --rm \
        --entrypoint /steamcmd/steamcmd.sh \
        -v "$STEAM_ROOT:/root/Steam" \
        "$IMAGE_NAME" \
        +force_install_dir /root/Steam \
        +login anonymous \
        +workshop_download_item "$WORKSHOP_APP_ID" "$MOD_ID" validate \
        +quit

    SRC="$WORKSHOP_CONTENT_DIR/$MOD_ID"

    if [ ! -f "$SRC/modinfo.lua" ]; then
        echo "ERROR: workshop-$MOD_ID downloaded but modinfo.lua not found."
        echo "Checked:"
        echo "$SRC"
        echo
        echo "Debug folders:"
        find "$STEAM_ROOT" -type d -name "$MOD_ID" 2>/dev/null || true
        exit 1
    fi

    rm -rf "$DEST"
    mkdir -p "$DEST"
    cp -a "$SRC/." "$DEST/"

    echo "Installed workshop-$MOD_ID"
done

echo
echo "Disabling DST auto workshop download..."

cat > "$SERVER_MODS_DIR/dedicated_server_mods_setup.lua" <<'EOF'
-- Auto Generated by GAMECONCAK
-- Local mods are installed manually into data/server/mods/workshop-*
-- Do not use ServerModSetup here.
EOF

generate_modoverrides() {
    OUTPUT="$1"
    mkdir -p "$(dirname "$OUTPUT")"

    {
        echo "return {"

        for MOD in "${MOD_IDS[@]}"
        do
            echo "    [\"workshop-$MOD\"] = {"
            echo "        enabled = true,"
            echo "        configuration_options = {}"
            echo "    },"
            echo
        done

        echo "}"
    } > "$OUTPUT"
}

echo "Generating modoverrides.lua..."

generate_modoverrides "$MASTER_MODOVERRIDES"
generate_modoverrides "$CAVES_MODOVERRIDES"

echo
echo "===================================="
echo " Local Mods Synced"
echo "===================================="
echo
echo "Enabled mods:"

for MOD in "${MOD_IDS[@]}"
do
    echo " - workshop-$MOD"
done