#!/bin/bash
set -e

############################################
# GAMECONCAK Mod Generator
############################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

SERVER_DIR="$PROJECT_DIR/data/server"
MODS_FILE="$PROJECT_DIR/mods/mods.txt"

MASTER_MODOVERRIDES="$PROJECT_DIR/config/cluster/Master/modoverrides.lua"
CAVES_MODOVERRIDES="$PROJECT_DIR/config/cluster/Caves/modoverrides.lua"

SERVER_MOD_SETUP="$SERVER_DIR/mods/dedicated_server_mods_setup.lua"

echo "===================================="
echo " GAMECONCAK Mod Generator"
echo "===================================="

############################################
# Check DST Server
############################################

if [ ! -f "$SERVER_DIR/bin64/dontstarve_dedicated_server_nullrenderer_x64" ]; then
    echo "ERROR: DST Dedicated Server not found."
    echo
    echo "Run:"
    echo "./scripts/update.sh"
    exit 1
fi

############################################
# Check mods.txt
############################################

if [ ! -f "$MODS_FILE" ]; then
    echo "ERROR: $MODS_FILE not found."
    exit 1
fi

mkdir -p "$SERVER_DIR/mods"

MOD_IDS=()

############################################
# Read mods.txt
############################################

while IFS= read -r LINE
do
    MOD_ID="$(echo "$LINE" | tr -d '[:space:]')"

    [[ -z "$MOD_ID" ]] && continue
    [[ "$MOD_ID" =~ ^# ]] && continue

    MOD_IDS+=("$MOD_ID")

done < "$MODS_FILE"

############################################
# Generate dedicated_server_mods_setup.lua
############################################

echo "Generating dedicated_server_mods_setup.lua..."

{
    echo "-- Auto Generated by GAMECONCAK"
    echo

    for MOD in "${MOD_IDS[@]}"
    do
        echo "ServerModSetup(\"$MOD\")"
    done

} > "$SERVER_MOD_SETUP"

############################################
# Generate modoverrides.lua
############################################

generate_modoverrides() {

    OUTPUT="$1"

    echo "Generating $(basename "$OUTPUT")..."

    {
        echo "return {"

        for MOD in "${MOD_IDS[@]}"
        do
            echo "    [\"workshop-$MOD\"] = {"
            echo "        enabled = true,"
            echo "        configuration_options = {}"
            echo "    },"
            echo
        done

        echo "}"

    } > "$OUTPUT"
}

generate_modoverrides "$MASTER_MODOVERRIDES"
generate_modoverrides "$CAVES_MODOVERRIDES"

echo
echo "===================================="
echo " Mod Files Generated"
echo "===================================="

echo "mods.txt                          OK"
echo "dedicated_server_mods_setup.lua   OK"
echo "Master/modoverrides.lua           OK"
echo "Caves/modoverrides.lua            OK"